### ISSUE TITLE
How to use with bleno

### ISSUE THREAD

**Issue by horihiro** [jasongin/noble-uwp#39]
Hi @jasongin !
This module is very useful because I no longer have to change a ble driver on Windows10.

I want to develop a software including [noble](https://github.com/sandeepmistry/noble) + [bleno](https://github.com/sandeepmistry/bleno).
But maybe noble-uwp doesn't work with bleno because each module require different driver.

Is there a way to use this with [bleno](https://github.com/sandeepmistry/bleno) ?
or do you have a plan to develop 'bleno-uwp' ?

**Comment by jasongin** [comment]
I have not looked into UWP support for `bleno`, and I have no plans to do so. I don't think the Windows UWP Bluetooth APIs even support having the Windows device act as a Bluetooth peripheral.
