### ISSUE TITLE
OS version requirement mismatch between README and code

### ISSUE THREAD

**Issue by enami** [jasongin/noble-uwp#59]
It looks like there is slight mismatch about required OS version between README and code.

The README says `Windows 10 build 10.0.15063 or later` is required while index.js checks if [OS version is 10.0.15014 or later](https://github.com/jasongin/noble-uwp/blob/master/index.js#L11).

**Comment by jasongin** [comment]
15014 was an intermediate (insiders) build, while 15063 was the released build. There's no reason to support old insiders builds, so `index.js` should probably be updated to 15063.
