### ISSUE TITLE
discoverSomeServices uses discoverAll (slow), and getGattServicesForUuidAsync does not accept valid guids

### ISSUE THREAD

**Issue by pursual** [jasongin/noble-uwp#85]
When telling this binding to discover a specific list of service uuids, it instead discovers all, and then filters the results. This is slow if you are working with a device with many services. 

I attempted to fix this, but no matter what I throw at getGattServicesForUuidAsync, it always returns "Bad arguments: No suitable overload found".

**Comment by pursual** [comment]
It doesnt appear that any methods in bindings JS call any of the C methods that accept a guid as an argument, so it is entirely possible that passing a guid to a C method is just broken.

**Comment by tony-gutierrez** [comment]
Figured out what was going on with the uuids. See https://github.com/jasongin/noble-uwp/pull/86

**Comment by pursual** [comment]
Closing for now as there is a path forward, or users can use the code in the PR

**Comment by jasongin** [comment]
I merged the PR. Thanks @tony-gutierrez !
